[package]
name = "muminst-rust-server"
version = "0.1.0"
edition = "2018"

[dependencies]
songbird = {version = "0.2.0"}
dotenv = {version = "0.15.0"}
tokio = {version = "1.9.0", features = ["full"]}
actix-web = "4.0.0-beta.8"
lazy_static = "1.4.0"

[dependencies.serenity]
default-features = false
features = [
    "client",
    "gateway",
    "model",
    "rustls_backend",
    "standard_framework",
    "voice",
    "cache",
]
version = "0.10.9"
