[package]
name = "muminst-rust-server"
version = "0.1.0"
edition = "2018"

[dependencies]
warp = "0.3"
tokio = { version = "1.12.0", features = ["full"] }
serenity = { default-features = false, features = ["client", "gateway", "model", 
"rustls_backend", "standard_framework", "voice", "cache"], version = "0.10.9"}
songbird = { version = "0.2.0"}
