# fly.toml file generated for muminst-server-rust on 2023-02-17T18:04:53+01:00

app = "muminst-server-rust"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  AUDIO_PATH = "/app/data/audio"
  DATABASE_PATH = "/app/data/database.db"
  RUST_BACKTRACE = "1"

[experimental]
  auto_rollback = true

[mounts]
  destination = "/app/data"
  source = "muminstserver_data"

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
