apiVersion: apps/v1
kind: Deployment
metadata:
  name: muminst-server-rust
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: muminst-server-rust
      version: v1
  template:
    metadata:
      labels:
        app: muminst-server-rust 
        version: v1
    spec:
      volumes:
      - name: muminst-server-rust-volume
        persistentVolumeClaim:
          claimName: muminst-server-rust-pv-claim-csi
      containers:
      - image: IMAGE:TAG 
        imagePullPolicy: IfNotPresent
        name: muminst-server-rust 
        ports:
        - containerPort: 8080 
        env:
        - name: DISCORD_TOKEN
          valueFrom:
            secretKeyRef:
              name: muminst-server-rust-secrets
              key: discord_bot_token
        - name: TELOXIDE_TOKEN
          valueFrom:
            secretKeyRef:
              name: muminst-server-rust-secrets
              key: telegram_bot_token
        - name: TELEGRAM_CHAT_ID 
          valueFrom:
            secretKeyRef:
              name: muminst-server-rust-secrets
              key: telegram_chat_id
        - name: DISCORD_GUILD_ID
          valueFrom:
            secretKeyRef:
              name: muminst-server-rust-secrets
              key: discord_guild_id 
        - name: DATABASE_PATH
          value: /app/data/database.db
        - name: AUDIO_PATH
          value: /app/data/audio
        - name: RUST_BACKTRACE
          value: "1" 
        resources:
          limits:
            cpu: 250m 
            memory: 256Mi
          requests:
            cpu: 100m 
            memory: 100Mi
        volumeMounts:
        - mountPath: /app/data
          name: muminst-server-rust-volume
